### ISSUE TITLE
Release v0.7 Tracker

### ISSUE THREAD

**Issue by cptrodgers** [cptrodgers/aj#8]
# Features

- [x] `AJ Plugin`. It will be a hook can run before (`pre_execute`) and after (`post_execute`) the result. Value for tracking, logger, realtime notification, etc. 
  - [x]  `JobPlugin` to control hook of job (change status, before, and after job execution).

- [x] Add `job_id` in Context to help access job id in execute logic and plugin. 

# Improvement
~- [ ] `Backend` trait v2 (the current trait doesn't reflect correct idea of Backend)~

# Breaking Changes
- [x] Migrate JobBuilder to in library code (without use `derive_builder`). It will break current job builder but we will make aj build job easily without unwrap.

```rust
let job = my_job.builder().retry(...); // No need handle JobBuilder Error
```

~- [ ] Migrate `chrono` to `std::time`.~
